[package]
name = "aoc2022"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7.4"
array_tool = "1.0.3"
regex = "1.7.0"
